"""Mini-ELF v17 — Part 1: audit the v16 residual failure.

Walks the v16 + v15 policy predictions, identifies every row whose
policy ``pass@5`` is False, dumps the full top-10 candidate list +
lean diagnostic for each one, and tries to read the held-out test
tactic so the reader can see the missing proof shape.

Produces:
  * ``data/baselines/v17_audit/audit.json``,
  * ``docs/V17_RESIDUAL_FAILURE_AUDIT.md``.

Confirms (or denies) the v17 brief's expectation that the only
remaining pass@5 failure is ``neg_exfalso_arrow_xy``.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("audit_v17_residual_failure")

V16_FAMILIES = ("forall_inst", "rewrite_succ", "neg_exfalso",
                "exists_reconstruct", "neg_imp_exfalso")


def _read_jsonl(p: Path) -> List[Dict[str, Any]]:
    if not p.exists():
        return []
    out: List[Dict[str, Any]] = []
    for ln in p.read_text(encoding="utf-8").splitlines():
        s = ln.strip()
        if not s or s.startswith("#"):
            continue
        out.append(json.loads(s))
    return out


def _load_test_index(fold_root: Path, fam: str) -> Dict[str, Dict[str, Any]]:
    out: Dict[str, Dict[str, Any]] = {}
    for r in _read_jsonl(fold_root / fam / "test.jsonl"):
        nm = r.get("theorem_name")
        if nm and nm not in out:
            out[nm] = r
    return out


def audit(v16_policy_root: Path, fold_root: Path,
          v16_token_root: Path) -> Dict[str, Any]:
    out: Dict[str, Any] = {"families": {}, "residual_failures": []}
    aggregate = {"n_rows": 0, "n_pass_at_5": 0, "n_fail_at_5": 0}
    for fam in V16_FAMILIES:
        fam_block = {"residual": [], "n_test_rows_unique": 0}
        out["families"][fam] = fam_block

        p_policy = v16_policy_root / fam / "policy" / "predictions.jsonl"
        if not p_policy.exists():
            continue
        rows = _read_jsonl(p_policy)
        test_index = _load_test_index(fold_root, fam)
        # raw v16 token (10-deep) lookup, for the verbatim error trace
        raw_pred_p = v16_token_root / fam / "raw" / "predictions.jsonl"
        raw_index: Dict[str, Dict[str, Any]] = {}
        for r in _read_jsonl(raw_pred_p):
            raw_index.setdefault(r["theorem_name"], r)

        unique_names: Dict[str, Dict[str, Any]] = {}
        for r in rows:
            unique_names.setdefault(r["theorem_name"], r)
        fam_block["n_test_rows_unique"] = len(unique_names)
        for nm, r in unique_names.items():
            aggregate["n_rows"] += 1
            if r.get("pass@5"):
                aggregate["n_pass_at_5"] += 1
                continue
            aggregate["n_fail_at_5"] += 1
            tm = test_index.get(nm) or {}
            raw_r = raw_index.get(nm) or {}
            failure = {
                "theorem_name": nm,
                "family": fam,
                "theorem_statement": tm.get("theorem_statement"),
                "state_before": tm.get("state_before"),
                "expected_tactic": tm.get("tactic"),
                "required_operation": tm.get("required_operation"),
                "policy_first_verified_rank": r.get("first_verified_rank"),
                "policy_pass@10": r.get("pass@10"),
                "raw_beam_candidates": list(raw_r.get("candidates") or [])[:10],
                "raw_beam_errors": [
                    (v.get("error") or "").splitlines()[0][:120]
                    for v in (raw_r.get("verifications") or [])[:10]
                ],
                "raw_beam_verified_indices": [
                    i for i, v in enumerate(raw_r.get("verifications") or [])
                    if v.get("success")
                ],
            }
            fam_block["residual"].append(failure)
            out["residual_failures"].append(failure)
    out["aggregate"] = aggregate
    return out


def write_markdown(out_md: Path, audit_obj: Dict[str, Any]) -> None:
    a = audit_obj["aggregate"]
    lines: List[str] = []
    lines.append("# Mini-ELF v17 — Residual Failure Audit")
    lines.append("")
    lines.append("Auto-generated by `scripts/audit_v17_residual_failure.py`. "
                 "Walks the v16 + v15-policy predictions for every v11 "
                 "LOFO test family and dumps the full top-10 trace for "
                 "rows where pass@5 fails — so the reader can see the "
                 "remaining proof shape gap.")
    lines.append("")
    lines.append(f"**Aggregate.** {a['n_pass_at_5']} / {a['n_rows']} "
                 f"unique theorems pass@5 ✓. **{a['n_fail_at_5']} residual "
                 f"failure(s).**")
    lines.append("")
    if not audit_obj["residual_failures"]:
        lines.append("No residual failures. v17 has nothing to do here.")
    for f in audit_obj["residual_failures"]:
        lines.append(f"## `{f['theorem_name']}` (`{f['family']}`)")
        lines.append("")
        lines.append(f"* **statement**: `{f['theorem_statement']}`")
        lines.append(f"* **state_before**:")
        lines.append("  ```")
        for ln in (f["state_before"] or "").split("\n"):
            lines.append(f"  {ln}")
        lines.append("  ```")
        lines.append(f"* **required_operation**: `{f['required_operation']}`")
        lines.append(f"* **expected (held-out) tactic**: "
                     f"`{f['expected_tactic']!r}`")
        lines.append(f"* **policy first_verified_rank**: "
                     f"`{f['policy_first_verified_rank']!r}`")
        lines.append(f"* **policy pass@10**: {f['policy_pass@10']}")
        lines.append("")
        lines.append("### v16 raw beam (top 10)")
        lines.append("")
        lines.append("| rank | candidate | error |")
        lines.append("|---:|---|---|")
        cands = f["raw_beam_candidates"]
        errs = f["raw_beam_errors"]
        for i in range(max(len(cands), len(errs))):
            c = (cands[i] if i < len(cands) else "—")
            c = (c if len(c) < 60 else c[:57] + "...")
            e = errs[i] if i < len(errs) else "—"
            lines.append(f"| {i} | `{c}` | `{e}` |")
        lines.append("")
        lines.append(
            "**Diagnosis.** No verifying candidate appears in the v16 "
            "beam. The held-out tactic uses the `(h hp).elim` "
            "False-elimination shape, which v16's `contrapositive_*` "
            "corpus does not include in this exact form (the v16 corpus "
            "has `False` as the *goal*; here `q` is the goal and `False` "
            "is intermediate). The v17 brief targets this gap.")
        lines.append("")
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text("\n".join(lines), encoding="utf-8")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--v16-policy-root",
                    default=str(ROOT / "data" / "baselines"
                                / "v16_policy_eval"))
    ap.add_argument("--v16-token-root",
                    default=str(ROOT / "data" / "baselines"
                                / "v16_token_seq2seq"))
    ap.add_argument("--fold-root",
                    default=str(ROOT / "data" / "processed"
                                / "proof_blocks_v11_family_lofo"))
    ap.add_argument("--out-json",
                    default=str(ROOT / "data" / "baselines"
                                / "v17_audit" / "audit.json"))
    ap.add_argument("--out-md",
                    default=str(ROOT / "docs"
                                / "V17_RESIDUAL_FAILURE_AUDIT.md"))
    args = ap.parse_args(argv)

    audit_obj = audit(Path(args.v16_policy_root), Path(args.fold_root),
                      Path(args.v16_token_root))
    out_json = Path(args.out_json)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(audit_obj, indent=2, ensure_ascii=False),
                        encoding="utf-8")
    write_markdown(Path(args.out_md), audit_obj)
    a = audit_obj["aggregate"]
    logger.info("v17 residual: %d failures / %d unique test rows",
                a["n_fail_at_5"], a["n_rows"])
    for f in audit_obj["residual_failures"]:
        logger.info("  %s  expected=%r required_op=%s",
                    f["theorem_name"], f["expected_tactic"],
                    f["required_operation"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
