"""Compose docs/V2_FAILURE_EXAMPLES.md from the per-eval failures_analysis.json
files (written by scripts/analyze_v2_failures.py). Read-only over metrics."""

from __future__ import annotations

import json
from pathlib import Path

B = Path("data/baselines")
OUT = Path("docs/V2_FAILURE_EXAMPLES.md")

SECTIONS = [
    ("v1 TRANSFER to the hard corpus (no retraining)", [
        ("hard hash", "hard_lean_cli_transfer_v1_hash_test"),
        ("hard family_holdout", "hard_lean_cli_transfer_v1_family_holdout_test"),
        ("hard difficulty_holdout", "hard_lean_cli_transfer_v1_difficulty_holdout_test"),
        ("hard adversarial_sibling", "hard_lean_cli_transfer_v1_adversarial_sibling_test"),
    ]),
    ("Mini-ELF v2 (trained on combined basic+hard)", [
        ("basic test (regression)", "combined_lean_cli_mini_elf_v2_basic_test"),
        ("hard hash", "combined_lean_cli_mini_elf_v2_hard_hash_test"),
        ("hard difficulty_holdout", "combined_lean_cli_mini_elf_v2_hard_difficulty_test"),
        ("hard adversarial_sibling", "combined_lean_cli_mini_elf_v2_hard_adversarial_test"),
    ]),
]


def _block(label: str, name: str) -> str:
    p = B / name / "failures_analysis.json"
    if not p.exists():
        return ""
    d = json.load(open(p, encoding="utf-8"))
    cal = d["reranker_calibration"]
    src = d["source_effectiveness"]
    lines = [f"### {label}  (`{name}`)", ""]
    lines.append(f"- reranker mean score: **verified={cal['mean_score_verified']}**, "
                 f"failed={cal['mean_score_failed']} "
                 f"(n_verified={cal['n_verified_scored']}, n_failed={cal['n_failed_scored']})")
    lines.append(f"- verified-by-source: {src['verified_by_source']}; "
                 f"reranker-rescued top-1: {src['rows_reranker_rescued_top1']}")
    lines.append(f"- failure taxonomy (failed top-1): {d['failure_taxonomy']}")
    ex = d.get("failure_taxonomy_examples", {})
    if ex:
        lines.append("- one example per error kind:")
        for kind, e in ex.items():
            lines.append(f"  - `{kind}`: {e['theorem']} — goal `{e['goal']}` → top1 `{e['top1']}`")
    fn = cal.get("top1_false_negatives") or []
    if fn:
        e = fn[0]
        lines.append(f"- false negative (verified candidate ranked below failed top-1): "
                     f"{e['theorem']} `{e['candidate']}` @rank {e['rank']} (score {e['score']})")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    out = [
        "# Mini-ELF v2 — failure examples & robustness analysis",
        "",
        "Generated by `scripts/compose_v2_failures.py` over the per-eval "
        "`failures_analysis.json` (from `scripts/analyze_v2_failures.py`), which "
        "read lean-verified predictions. Reruns: `scripts/run_v1_transfer_eval.sh`, "
        "`scripts/run_mini_elf_v2_eval.sh`, then this script.",
        "",
    ]
    for title, items in SECTIONS:
        blocks = [_block(lbl, name) for lbl, name in items]
        blocks = [b for b in blocks if b]
        if not blocks:
            continue
        out.append(f"## {title}")
        out.append("")
        out.extend(blocks)
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
