"""Compose ``docs/V3_FAILURE_EXAMPLES.md`` from the Lean-verified v3 predictions.

For each evaluated split it reports: the planner's contribution, reranker
calibration on the *planner* candidates (the v2 reranker is still mis-calibrated
off-distribution — v3 deliberately does not let it reorder the planner blocks),
per-strategy verified counts, **examples of newly-solved multi-step proofs**,
and **remaining failures** (pass@1 misses and any pass@5 miss). Reads
predictions only (theorem-level; never ``state_after``).
"""

from __future__ import annotations

import argparse
import statistics
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from mini_elf_lean.io_utils import read_jsonl  # noqa: E402
from mini_elf_lean.proof_planner import PLANNER_SOURCES  # noqa: E402

SPLITS = [
    ("hard difficulty_holdout (TARGET)", "mini_elf_v3_hard_difficulty_test"),
    ("hard adversarial_sibling", "mini_elf_v3_hard_adversarial_test"),
    ("hard hash", "mini_elf_v3_hard_hash_test"),
    ("basic test (regression)", "mini_elf_v3_basic_test"),
]
_PLANNER = set(PLANNER_SOURCES)


def _goal(state_before: str) -> str:
    return state_before.split("⊢")[-1].strip()


def analyze_split(pred_path: Path) -> Dict[str, Any]:
    rows = list(read_jsonl(pred_path))
    n = len(rows)
    pass1 = pass5 = 0
    rr_verified: List[float] = []
    rr_failed: List[float] = []
    solved_examples: List[Dict[str, str]] = []
    pass1_misses: List[Dict[str, str]] = []
    pass5_misses: List[Dict[str, str]] = []

    for row in rows:
        pk = row.get("lean_pass_at_k", {})
        if pk.get("1"):
            pass1 += 1
        passed5 = bool(pk.get("5"))
        if passed5:
            pass5 += 1
        preds = row.get("predictions") or []
        prov = row.get("prediction_provenance") or []
        lean = row.get("lean_results") or {}
        goal = _goal(row.get("state_before", ""))
        name = row.get("theorem_name", "")

        # reranker calibration on planner candidates only
        for i, tac in enumerate(preds):
            p = prov[i] if i < len(prov) else {}
            if p.get("source") in _PLANNER and p.get("reranker_score") is not None:
                ok = bool(lean.get(tac, {}).get("success"))
                (rr_verified if ok else rr_failed).append(float(p["reranker_score"]))

        # a multi-step planner solve at top-1 (chain/cases/eq/iff, multi-line or composed)
        if preds and pk.get("1"):
            p0 = prov[0] if prov else {}
            src = p0.get("source")
            tac0 = preds[0]
            if src in ("planner_chain", "planner_cases", "planner_eq", "planner_iff") and len(solved_examples) < 8:
                solved_examples.append({
                    "theorem_name": name, "goal": goal,
                    "tactic": tac0.replace("\n", "\\n"),
                    "strategy": p0.get("strategy") or "?", "source": src,
                })

        # remaining failures
        if not pk.get("1"):
            # find the verified rank (if any in top-5)
            vrank = next((i + 1 for i, t in enumerate(preds) if lean.get(t, {}).get("success")), None)
            rec = {"theorem_name": name, "goal": goal,
                   "top1": (preds[0] if preds else "").replace("\n", "\\n"),
                   "verified_rank": str(vrank) if vrank else "none(top5)"}
            (pass1_misses if passed5 else pass5_misses).append(rec)

    def _mean(xs: List[float]) -> Optional[float]:
        return round(statistics.mean(xs), 4) if xs else None

    return {
        "n": n,
        "pass_at_1": pass1 / n if n else 0.0,
        "pass_at_5": pass5 / n if n else 0.0,
        "rr_verified_mean": _mean(rr_verified),
        "rr_failed_mean": _mean(rr_failed),
        "rr_verified_count": len(rr_verified),
        "rr_failed_count": len(rr_failed),
        "solved_examples": solved_examples,
        "pass1_misses": pass1_misses,
        "pass5_misses": pass5_misses,
    }


def render(reports: List[Dict[str, Any]]) -> str:
    L: List[str] = []
    L.append("# Mini-ELF v3 — solved-proof & remaining-failure examples\n")
    L.append(
        "Generated by `scripts/compose_v3_examples.py` over the Lean-verified v3 "
        "predictions (`scripts/run_mini_elf_v3_eval.sh`). v3 = the symbolic "
        "proof-block **planner** (`mini_elf_lean/proof_planner.py`) fused with the "
        "v2 model + reranker + witness-copy. Theorem-level only; the planner is "
        "symbolic/heuristic, not neural generation; not full ELF.\n"
    )
    for title, rep in reports:
        L.append(f"\n## {title}  (`{rep['_dir']}`)\n")
        L.append(f"- n={rep['n']}  ·  `pass@1`=**{rep['pass_at_1']:.3f}**  ·  "
                 f"`pass@5`=**{rep['pass_at_5']:.3f}**")
        L.append(f"- reranker score on *planner* candidates: "
                 f"verified={rep['rr_verified_mean']} (n={rep['rr_verified_count']}), "
                 f"failed={rep['rr_failed_mean']} (n={rep['rr_failed_count']}) "
                 f"— recorded for calibration; the planner is ordered by its own "
                 f"symbolic priority, **not** by this score.")
        if rep["solved_examples"]:
            L.append("\n**Newly-solved multi-step proofs (planner top-1, Lean-verified):**")
            for e in rep["solved_examples"]:
                L.append(f"- `{e['theorem_name']}` [{e['source']}/{e['strategy']}] "
                         f"goal `⊢ {e['goal']}` → `{e['tactic']}`")
        if rep["pass5_misses"]:
            L.append(f"\n**Unsolved at pass@5 ({len(rep['pass5_misses'])}):**")
            for e in rep["pass5_misses"][:8]:
                L.append(f"- `{e['theorem_name']}` goal `⊢ {e['goal']}` → top1 `{e['top1']}`")
        else:
            L.append("\n**Unsolved at pass@5: none.**")
        if rep["pass1_misses"]:
            L.append(f"\n**Solved within top-5 but not top-1 ({len(rep['pass1_misses'])}):**")
            for e in rep["pass1_misses"][:8]:
                L.append(f"- `{e['theorem_name']}` goal `⊢ {e['goal']}` → top1 `{e['top1']}` "
                         f"(verified at rank {e['verified_rank']})")
        L.append("")
    return "\n".join(L)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=ROOT / "docs/V3_FAILURE_EXAMPLES.md")
    args = ap.parse_args(argv)
    reports = []
    for title, d in SPLITS:
        pred = ROOT / "data/baselines" / d / "predictions.jsonl"
        if not pred.exists():
            continue
        rep = analyze_split(pred)
        rep["_dir"] = d
        reports.append((title, rep))
    args.out.write_text(render(reports), encoding="utf-8")
    print(f"wrote {args.out}")
    for title, rep in reports:
        print(f"  {title}: pass@1={rep['pass_at_1']:.3f} pass@5={rep['pass_at_5']:.3f} "
              f"rr_verified={rep['rr_verified_mean']} rr_failed={rep['rr_failed_mean']} "
              f"pass1_misses={len(rep['pass1_misses'])} pass5_misses={len(rep['pass5_misses'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
